// tools/lib/reference.mjs
const ACRONYMS = new Set(['cdk']);
function titleCase(name) {
  return name.split('-').map((w) => ACRONYMS.has(w) ? w.toUpperCase() : w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

export function officialUrl(name, category) {
  if (category === 'guide') return `https://material.angular.dev/guide/${name}`;
  if (name.startsWith('cdk-')) return `https://material.angular.dev/cdk/${name.slice(4)}/overview`;
  return `https://material.angular.dev/components/${name}/overview`;
}

export function referenceHeader({ name, category, tag, includeTitle = true }) {
  const url = officialUrl(name, category);
  return [
    `<!-- GENERATED by angular-material-skill from angular/components@${tag}. Do not edit by hand. -->`,
    '',
    ...(includeTitle ? [`# ${titleCase(name)}`, ''] : []),
    `> Source: [official documentation](${url}) — derived from ` +
      `[\`angular/components\`](https://github.com/angular/components) (${tag}), MIT license. See NOTICE.`,
    '',
    '',
  ].join('\n');
}
